import { serve } from 'https://deno.land/std@0.208.0/http/server.ts'
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.39.3?target=deno'
import { sendEmail } from '../_shared/resend.ts'
import he from 'https://esm.sh/he@1.2.0'

const ALLOWED_ORIGINS = new Set([
  'https://digitalrelative.co.uk',
  'https://www.digitalrelative.co.uk',
  'https://legatum-chi.vercel.app',
  'https://digital-relative.vercel.app',
])

function getCorsHeaders(origin: string): Record<string, string> {
  if (!ALLOWED_ORIGINS.has(origin)) return {}
  return {
    'Access-Control-Allow-Origin': origin,
    'Access-Control-Allow-Headers': 'content-type',
    'Access-Control-Allow-Methods': 'POST, OPTIONS',
    'Vary': 'Origin',
  }
}

serve(async (req) => {
  const origin = req.headers.get('origin') || ''
  const hdrs   = getCorsHeaders(origin)

  if (req.method === 'OPTIONS') return new Response('ok', { headers: hdrs })
  if (req.method !== 'POST')    return new Response('Method not allowed', { status: 405 })

  const contentLength = parseInt(req.headers.get('content-length') || '0')
  if (contentLength > 1024) return new Response('Payload too large', { status: 413 })

  const supabase = createClient(
    Deno.env.get('SUPABASE_URL')!,
    Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
  )

  try {
    const body = await req.json().catch(() => null)
    if (!body?.token) {
      return new Response(JSON.stringify({ error: 'Invalid request' }), {
        status: 400, headers: { ...hdrs, 'Content-Type': 'application/json' },
      })
    }

    const { token } = body

    // Rate limit by IP — max 10 attempts per 15 minutes
    const clientIp = req.headers.get('x-forwarded-for')?.split(',')[0]?.trim() || ''
    // NEW-9 fix: reject requests with no IP header (direct invocation bypassing proxy)
    if (!clientIp) {
      return new Response(JSON.stringify({ error: 'Invalid request' }), {
        status: 400, headers: { ...hdrs, 'Content-Type': 'application/json' },
      })
    }
    if (clientIp !== 'unknown') {
      const windowStart = new Date(Date.now() - 15 * 60 * 1000).toISOString()
      const { count } = await supabase
        .from('rate_limits')
        .select('*', { count: 'exact', head: true })
        .eq('identifier', clientIp)
        .eq('action', 'beneficiary_access')
        .gt('window_start', windowStart)
      if ((count ?? 0) >= 10) {
        await new Promise(r => setTimeout(r, 200))
        // Record access timestamp on each entry (best-effort, non-blocking)
    return new Response(JSON.stringify({ error: 'Too many requests' }), {
          status: 429, headers: { ...hdrs, 'Content-Type': 'application/json' },
        })
      }
      // Log this attempt
      await supabase.from('rate_limits').insert({ identifier: clientIp, action: 'beneficiary_access', attempts: 1 }).catch(() => {})
    }

    if (!/^[0-9a-f]{64}$/.test(token)) {
      // Record access timestamp on each entry (best-effort, non-blocking)
    return new Response(JSON.stringify({ error: 'Not found' }), {
        status: 404, headers: { ...hdrs, 'Content-Type': 'application/json' },
      })
    }

    // CRIT-1 fix: look up by invite_token OR emergency_access_token
    // emergency_access_token is generated by grantVaultAccess and emailed to beneficiaries
    const { data: beneficiary, error: benError } = await supabase
      .from('beneficiaries')
      // group_name intentionally excluded - owner-only organisational label, must never be visible to beneficiaries
      .select('id, user_id, name, email, relation, access_level, access_requirement, status, id_verified_at, is_executor')
      .or(`invite_token.eq.${token},emergency_access_token.eq.${token}`)
      .in('status', ['email_confirmed', 'id_verified', 'access_granted'])
      .single()

    if (benError || !beneficiary) {
      // Constant-time response to prevent timing-based token enumeration
      await new Promise(r => setTimeout(r, 200))
      return new Response(JSON.stringify({ error: 'Not found' }), {
        status: 404, headers: { ...hdrs, 'Content-Type': 'application/json' },
      })
    }

    // C-3 fix: reject expired access tokens
    if (beneficiary.token_expires_at && new Date(beneficiary.token_expires_at) < new Date()) {
      return new Response(JSON.stringify({ error: 'Access link has expired' }), {
        status: 401, headers: { ...hdrs, 'Content-Type': 'application/json' },
      })
    }

    const isTier2      = !!beneficiary.id_verified_at
    const ownerId      = beneficiary.user_id
    const accessLevel  = beneficiary.access_level || 'Full access'
    const accessReq    = beneficiary.access_requirement || 'death_certificate'

    const { data: guide } = await supabase
      .from('after_i_am_gone')
      .select('guide_data')
      .eq('user_id', ownerId)
      .single()

    // H-1 fix: enforce access_level server-side — not just tier
    // Read only: titles and categories only regardless of ID verification
    // Full access + Tier 2: also username and notes
    // Specific categories only: only entries explicitly shared with this beneficiary
    let entrySelect = 'id, title, category'
    if (isTier2 && accessLevel === 'Full access') {
      entrySelect = 'id, title, category, username, notes'
    }

    let entryQuery = supabase.from('vault_entries').select(entrySelect).eq('user_id', ownerId)
    let vaultEntries: any[] = []

    if (accessLevel === 'Specific categories only') {
      // Fetch only entries explicitly shared with this beneficiary via junction table
      const { data: sharedLinks } = await supabase
        .from('beneficiary_shared_entries')
        .select('entry_id')
        .eq('beneficiary_id', beneficiary.id)

      const sharedIds = (sharedLinks || []).map((l: any) => l.entry_id)
      if (sharedIds.length > 0) {
        const { data } = await entryQuery.in('id', sharedIds)
        vaultEntries = data || []
      }
    } else {
      const { data } = await entryQuery
      vaultEntries = data || []
    }

    // Record access timestamp on each entry (best-effort, non-blocking)
    // Record last accessed time on each vault entry (best-effort, non-blocking)
    if (vaultEntries.length > 0) {
      supabase.from('vault_entries')
        .update({ last_accessed_at: new Date().toISOString() })
        .eq('user_id', beneficiary.user_id)
        .catch(() => {})
    }

    // Geographic access alert - notify owner if access from outside UK
    const accessCountry = req.headers.get('cf-ipcountry') || ''
    if (accessCountry && accessCountry !== 'XX' && accessCountry !== 'GB') {
      const { data: ownerAuth } = await supabase.auth.admin.getUserById(beneficiary.user_id)
      const ownerEmail   = ownerAuth?.user?.email
      const rawOwnerName = (ownerAuth?.user?.user_metadata?.full_name || 'there').replace(/[\r\n]/g, ' ').slice(0, 100)
      const benName      = (beneficiary.name || 'A beneficiary').replace(/[\r\n]/g, ' ').slice(0, 100)
      const time         = new Date().toLocaleString('en-GB', { timeZone: 'Europe/London', dateStyle: 'medium', timeStyle: 'short' })
      if (ownerEmail) {
        sendEmail({
          to:      ownerEmail,
          subject: '⚠️ Digital Relative - Vault accessed from outside the UK',
          html:    `<div style="font-family:sans-serif;max-width:520px;margin:0 auto;padding:24px;background:#0d1e30;color:#e8e2d4;">
            <h2 style="color:#c9a84c;">Vault access alert</h2>
            <p><strong>${he(benName)}</strong> accessed your vault at ${he(time)} from country code <strong>${he(accessCountry)}</strong> (outside the UK).</p>
            <p>If this was expected, no action is needed. If not, sign in to Digital Relative and review your beneficiary settings.</p>
          </div>`,
        }).catch(() => {})
      }
    }

    return new Response(JSON.stringify({
      beneficiary: {
        id:           beneficiary.id,
        name:         beneficiary.name,
        email:        beneficiary.email,
        relation:     beneficiary.relation,
        access_level: beneficiary.access_level,
        status:       beneficiary.status,
        id_verified_at: beneficiary.id_verified_at,
        is_executor:      beneficiary.is_executor,
        access_requirement: accessReq,
        // user_id intentionally omitted - L-1 fix: no need to expose owner UUID to caller
      },
      guide: {
        sections:       guide?.guide_data?.sections || null,
        personalMessage: guide?.guide_data?.personalMessage || '',
        funeralWishes:  guide?.guide_data?.funeralWishes || null,
      },
      vaultEntries: vaultEntries || [],
      isTier2,
      accessLevel,
      accessRequirement: accessReq,
    }), {
      headers: { ...hdrs, 'Content-Type': 'application/json' },
    })

  } catch {
    // Record access timestamp on each entry (best-effort, non-blocking)
    return new Response(JSON.stringify({ error: 'Internal error' }), {
      status: 500, headers: { ...hdrs, 'Content-Type': 'application/json' },
    })
  }
})
